### ISSUE TITLE
Supporting latest version of Forge2d

### ISSUE THREAD

**Issue by bmd007** [aeb-dev/flame_forge2d_tiled#4]
Hi

Any plans for supporting the latest version of Forge2D? 

Thanks in advance

**Comment by aeb-dev** [comment]
Sure, I will try to implement it in the weekend

**Comment by bmd007** [comment]
any updates @aeb-dev sir?

**Comment by aeb-dev** [comment]
I am still working on it. I was implementing multiple features before, so I am combining them all currently. It might take a little while

**Comment by aeb-dev** [comment]
I just published the package, you can use it with flame 1.6.0
